import "./styles.scss";
import "./defaultData.ts";
import "./render.ts";
import "./filter.ts";
import "./order.ts";
import "./search.ts";
import "./slider.ts";
import "./reset.ts";
import { setDefaultSettings } from "./defaultData";
setDefaultSettings();
